var MENUDATA = [
    {
        title:'弹出层', 
        name:'layer',
        desc:'支持alert、confirm、tips、iframe、自适应等...'
    },
    {
        title:'抽奖', 
        name:'lottery',
        desc:'宫格、旋转2种方式，可自定义数量'
    },
	{
		title:'模版引擎', 
        name:'arttemplate',
        desc:'性能卓越的javascript模板引擎'
	}
	,
	{
		title:'活动倒计时', 
        name:'timer',
        desc:'可满足各类活动倒计时，自定义显示方式'
	}
]